name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Display Go Version
        run: go version

      - name: Display Go Location
        run: which go

      - name: Display Go Path
        run: echo $GOPATH

      - name: Display Go Root
        run: echo $GOROOT

      - name: Display Go Env
        run: go env

      - name: Build
        run: make build

      - name: Test
        run: go test -v ./...
